### ISSUE TITLE
node index.js 実行時に HostNotFoundError が発生しました

### ISSUE THREAD

**Issue by rev01c** [nnn-training/secret-board-3023#11]
cookiesモジュールをインストールしよう のところでコードを修正して node index.js を実行したところ、以下のエラーが発生しました。
docker-compose.yml の db image を postgres:12 にしたところエラーは起きなくなりました。

```
root@99b6d8630287:/app# node index.js
Listening on 8000
/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:175
                reject(new sequelizeErrors.HostNotFoundError(err));
                       ^

HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND db
    at Client._connectionCallback (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:175:24)
    at Client._handleErrorWhileConnecting (/app/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/app/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (node:events:526:28)
    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:53:12)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  parent: Error: getaddrinfo ENOTFOUND db
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'db'
  },
  original: Error: getaddrinfo ENOTFOUND db
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'db'
  }
}
```

**Comment by rev01c** [comment]
すみません、実行ブランチが main-2022 だからでした 🙇 
本件クローズいたします、お騒がせしました。。。
